# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
    
trigger:
- master

pr: none

extends:
  template: base.yml
  parameters:
    stages:
    - stage:
      displayName: Build app
      jobs:
        - template: job.template.yml
          parameters:
            name: linux
            pool:
              vm: linux-latest